language: bash
services: docker
env:
    - APACHE_WEB_ROOT=/var/www
install:
    - docker build -t moodle-php-apache .
before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
script:
    - docker run --name test0 -t -d -p 8000:80 -v $PWD/tests/fixtures:/var/www/html moodle-php-apache
    - docker exec test0 php /var/www/html/test.php
    - curl --fail http://127.0.0.1:8000/test.php
    #now run with environment variables, we should get the same type of test pass
    - docker run --name test1 -t -d -e APACHE_WEB_ROOT -p 8001:80 -v $PWD/tests/fixtures:/var/www moodle-php-apache
    - docker exec test1 php /var/www/test.php
    - curl --fail http://127.0.0.1:8001/test.php
after_failure:
    - docker logs test0 && docker logs test1
after_success:
  - docker push $DOCKER_USERNAME/moodle-php-apache:7.1;
after_script:
    - docker rm -f test0 test1
